name: Build Latex
on:
    push:
      branches: [ main ]
    workflow_dispatch :
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: doc
          root_file: thesis.tex
          args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode -shell-escape -bibtex -f

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - name: Rename file 
        run: mv thesis.pdf ${{ github.event.repository.name }}_${{ steps.date.outputs.date }}.pdf
        
      - name: Upload document
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}_${{ steps.short-sha.outputs.sha }}
          path: ${{ github.event.repository.name }}_${{ steps.date.outputs.date }}.pdf
