name: Build on Host
on:
    push:
      branches: [ main ]
    workflow_dispatch :
jobs:
    build_latex:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v1
        - uses: BSFishy/meson-build@v1.0.3
          with:
            action: test
            directory: build